# Generated by Django 4.1.3 on 2022-11-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
